### ISSUE TITLE
Remove six from setup.py

### ISSUE THREAD

**Issue by abhinavramana** [kissgyorgy/enum34-custom#5]
Hi,

This package does not install cleanly because it doesn't package self-sufficiently. Currently in `setup.py` it imports `six` as `setupRequires` without declaring that.
`import six` in `setup.py` should be removed. Instead we should use `sys.version_info[0]` to compare the python version. For example:

import sys
from setuptools import setup, find_packages
from setuptools.command.test import test as TestCommand
if sys.version_info[0] < 3:
install_requires = ['six', 'enum34']
else:
install_requires = ['six']

**Comment by kissgyorgy** [comment]
LOL what a stupid mistake, thank you, I will fix this.

**Comment by abhinavramana** [comment]
Thank you so much for this. Is there any ETA for this?
